//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServiceXyz")]
    public interface IServiceXyz {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceXyz/GetCustomers", ReplyAction="http://tempuri.org/IServiceXyz/GetCustomersResponse")]
        WCF_XYZ.CustomerData[] GetCustomers(WCF_XYZ.CustomerData cust);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceXyz/GetCustomers", ReplyAction="http://tempuri.org/IServiceXyz/GetCustomersResponse")]
        System.Threading.Tasks.Task<WCF_XYZ.CustomerData[]> GetCustomersAsync(WCF_XYZ.CustomerData cust);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceXyz/GetCustomersForUpdate", ReplyAction="http://tempuri.org/IServiceXyz/GetCustomersForUpdateResponse")]
        WCF_XYZ.CustomerData[] GetCustomersForUpdate(string partner, int qtdValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceXyz/GetCustomersForUpdate", ReplyAction="http://tempuri.org/IServiceXyz/GetCustomersForUpdateResponse")]
        System.Threading.Tasks.Task<WCF_XYZ.CustomerData[]> GetCustomersForUpdateAsync(string partner, int qtdValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceXyz/SetCustomers", ReplyAction="http://tempuri.org/IServiceXyz/SetCustomersResponse")]
        WCF_XYZ.CustomerError[] SetCustomers(string partner, WCF_XYZ.CustomerData[] cust);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceXyz/SetCustomers", ReplyAction="http://tempuri.org/IServiceXyz/SetCustomersResponse")]
        System.Threading.Tasks.Task<WCF_XYZ.CustomerError[]> SetCustomersAsync(string partner, WCF_XYZ.CustomerData[] cust);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceXyzChannel : Example.ServiceReference1.IServiceXyz, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceXyzClient : System.ServiceModel.ClientBase<Example.ServiceReference1.IServiceXyz>, Example.ServiceReference1.IServiceXyz {
        
        public ServiceXyzClient() {
        }
        
        public ServiceXyzClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceXyzClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceXyzClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceXyzClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCF_XYZ.CustomerData[] GetCustomers(WCF_XYZ.CustomerData cust) {
            return base.Channel.GetCustomers(cust);
        }
        
        public System.Threading.Tasks.Task<WCF_XYZ.CustomerData[]> GetCustomersAsync(WCF_XYZ.CustomerData cust) {
            return base.Channel.GetCustomersAsync(cust);
        }
        
        public WCF_XYZ.CustomerData[] GetCustomersForUpdate(string partner, int qtdValue) {
            return base.Channel.GetCustomersForUpdate(partner, qtdValue);
        }
        
        public System.Threading.Tasks.Task<WCF_XYZ.CustomerData[]> GetCustomersForUpdateAsync(string partner, int qtdValue) {
            return base.Channel.GetCustomersForUpdateAsync(partner, qtdValue);
        }
        
        public WCF_XYZ.CustomerError[] SetCustomers(string partner, WCF_XYZ.CustomerData[] cust) {
            return base.Channel.SetCustomers(partner, cust);
        }
        
        public System.Threading.Tasks.Task<WCF_XYZ.CustomerError[]> SetCustomersAsync(string partner, WCF_XYZ.CustomerData[] cust) {
            return base.Channel.SetCustomersAsync(partner, cust);
        }
    }
}
