//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_XYZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustId { get; set; }
        public string CustName { get; set; }
        public Nullable<System.DateTime> CustBirthDate { get; set; }
        public string CustPhone { get; set; }
        public string CustAddr { get; set; }
        public string CustZip { get; set; }
        public string CustCity { get; set; }
        public string CustState { get; set; }
        public string CustCellPhone { get; set; }
    
        public virtual PartnerCustomer PartnerCustomer { get; set; }
    }
}
